### ISSUE TITLE
starter projectの追加

### ISSUE THREAD

**Issue by yk-saito** [unchain-tech/ETH-NFT-Collection#4]
~~- 別ブランチに追加~~
- starterをmainブランチに、現mainをcompleteブランチに変更
- 該当ブランチからクローンするよう、学習コンテンツを修正

**Comment by yk-saito** [comment]
[starterブランチ](https://github.com/unchain-tech/ETH-NFT-Collection/tree/starter)に追加しました。

**Comment by neila** [comment]
Draftみたのですが、学習コンテンツ側、`starter` のみcloneするようになってる箇所が見当たらなかったです 🙏🏽

**Comment by yk-saito** [comment]
> Draftみたのですが、学習コンテンツ側、`starter` のみcloneするようになってる箇所が見当たらなかったです 🙏🏽

失礼しました🙇
反映いたしましたので、ご確認お願いします！（[docs/ETH-NFT-Collection/ja/section-3/lesson-1_Reactとウォレットをセットアップしよう.md - diff](https://github.com/unchain-tech/UNCHAIN-projects/pull/339/files#diff-0ed03e9216a4a8e5e945319f53d0c448418719fa2123391ed827ed7cd13445af)）
